<script type="text/javascript">
//<![CDATA[
var MSG_ADDITEM_JS_EDIT = _("Modifier");
var MSG_ADDITEM_JS_DELETE = _("Supprimer");
var MSG_ADDITEM_JS_CLEAR = _("Effacer");
var MSG_ADDITEM_JS_CANT_RECEIVE_MORE_ITEMS = _("Vous ne pouvez pas recevoir plus d'exemplaires");
var MSG_ADDITEM_JS_IS_DUPLICATE = _("est un doublon");
var MSG_ADDITEM_JS_ALREADY_EXISTS_IN_DB = _("already exists in database");
//]]>
</script>
