<tfoot>
 <tr>
 <td colspan="6" style="text-align: right; font-weight:bold;">Total&nbsp;:</td>
 <td>[% totaldue %]</td>
 <td>[% totalprice %]</td>
 <td colspan="3"><div class="date-select">
 <p><label for="newduedate">Renewal due date:</label> <input type="text" size="12" id="newduedate" name="newduedate" value="[% newduedate %]" readonly="readonly" />
</p>
 <p><label for="exemptfine">Effacer les amendes au retour&nbsp;:<input type="checkbox" id="exemptfine" name="exemptfine" value="1" /></label></p></div>
 </td>
 </tr>
</tfoot>
