<script type="text/javascript">
//<![CDATA[
    var MSG_DT_FIRST = _("Premier");
    var MSG_DT_LAST = _("Last");
    var MSG_DT_NEXT = _("Suivant");
    var MSG_DT_PREVIOUS = _("Précédent");
    var MSG_DT_EMPTY_TABLE = _("Pas de donnée disponible");
    var MSG_DT_INFO = _("Showing _START_ to _END_ of _TOTAL_");
    var MSG_DT_INFO_EMPTY = _("Pas d'entrée à afficher");
    var MSG_DT_INFO_FILTERED = _("(filtered from _MAX_ total entries)");
    var MSG_DT_LENGTH_MENU = _("Montrer_MENU_ entrées");
    var MSG_DT_LOADING_RECORDS = _("Loading...");
    var MSG_DT_PROCESSING = _("En cours...");
    var MSG_DT_SEARCH = _("Rechercher:");
    var MSG_DT_ZERO_RECORDS = _("Pas de notices correspondantes trouvées.");
//]]>
</script>
