<h5>Exécuter le rapport</h5>
<ul>
 [% IF ( CAN_user_reports_execute_reports ) %]<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Use%20saved">Rapports sauvegardés</a></li>[% END %] </ul>
<h5>Dictionnaire des rapports</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View%20Dictionary">Voir dictionnaire</a></li>
</ul>
<h5>Ressources utiles</h5>
<ul>
<li><a href="http://wiki.koha-community.org/wiki/SQL_Reports_Library" target="blank">Bibliothèque de rapports Koha</a></li>
<li><a href="http://schema.koha-community.org/" target="blank">Schéma de la base de données Koha</a></li>
</ul>
