<form action="/cgi-bin/koha/edithelp.pl" method="post">
 <fieldset class="action"><input value="Fermer la fenêtre d'aide" type="button" class="submit" onclick="window.close(); return false;" />
 <input type="hidden" name="type" value="modify" />
 <input type="hidden" name="referer" value="[% referer %]" />
 <input value="Ajouter de l'aide" type="submit" class="submit" /></fieldset>
</form>
</body>
</html>
