<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-layout.pl?op=new">Ajouter format</a>
 </div>

 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-template.pl?op=new">Nouveau modèle</a>
 </div>

 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-profile.pl?op=new">Nouveau profil</a>
 </div>

 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-batch.pl?op=new">Ajouter un lot</a>
 </div>
</div>