<div id="toolbar" class="btn-toolbar">
 <a class="btn btn-small" id="layouts" href="/cgi-bin/koha/patroncards/edit-layout.pl?op=new">Ajouter format</a>
 <a class="btn btn-small" id="templates" href="/cgi-bin/koha/patroncards/edit-template.pl?op=new">Nouveau modèle</a>
 <a class="btn btn-small" id="profiles" href="/cgi-bin/koha/patroncards/edit-profile.pl?op=new">Nouveau profil</a>
 <a class="btn btn-small" id="batches" href="/cgi-bin/koha/patroncards/edit-batch.pl?op=new">Ajouter un lot</a>
</div>
