<div id="navmenu"><ul id="navmenulist">
 <li><a href="/cgi-bin/koha/patroncards/home.pl">Créateur de cartes adhérent</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Gérer les formats</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Gérer les modèles</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Gérer les profils</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Gérer les lots</a></li>
 <li><a href="/cgi-bin/koha/patroncards/image-manage.pl">Gérer les images</a></li>
</ul>
</div>
