<a onclick="javascript:if (document.getElementsByName('Coded_Fields')[0].style.display=='none'){document.getElementsByName('Coded_Fields')[0].style.display='block';} else {document.getElementsByName('Coded_Fields')[0].style.display='none';}">Plus d'information</a>
<div id="yui-b" style="display:none;" name="Coded_Fields" >
<!-- SUBTYPE LIMITS -->
 <fieldset>
 <legend>Champs codés</legend>
 <p>
 <label>Audience</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tous</option>
 <option value="aud:a">jeunesse, général</option>
 <option value="aud:b">pre-primary (0-5)</option>
 <option value="aud:c">primary (5-8)</option>
 <option value="aud:d">enfants (9-14)</option>
 <option value="aud:e">young adult</option>
 <option value="aud:k">adult, serious</option>
 <option value="aud:m">adult, general</option>
 <option value="aud:u">inconnu</option>
 </select>
 </p>
 <p>
 <label>Imprimer</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tous</option>
 <option value="Material-type:r">Impression normale</option>
 <option value="Material-type:d">Gros caractères</option>
 <option value="Material-type:e">format journal</option>
 <option value="Material-type:f">Script Braille ou Moon</option>
 <option value="Material-type:g">micro-impression</option>
 <option value="Material-type:h">manuscrit</option>
 <option value="Material-type:i">multimedia</option>
 <option value="Material-type:j">mini-impression</option>
 <option value="Material-type:s">electronic ressource</option>
 <option value="Material-type:t">microforme</option>
 <option value="Material-type:z">autre forme de document textuel</option>
 </select>
 </p>
 <p>
 <label>Literary genre</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tous</option>
 <option value="Literature-Code:a">fiction</option>
 <option value="Literature-Code:b">drama</option>
 <option value="Literature-Code:c">essais</option>
 <option value="Literature-Code:d">humour, satire</option>
 <option value="Literature-Code:e">lettres</option>
 <option value="Literature-Code:f">nouvelles</option>
 <option value="Literature-Code:g">poetry</option>
 <option value="Literature-Code:h">discours, art oratoire</option>
 <option value="Literature-Code:i">libretto</option>
 <option value="Literature-Code:y">n'est pas un texte littéraire</option>
 <option value="Literature-Code:z">multiple/other literary forms</option>
 </select>
 </p>
 <p>
 <label>Biographie</label>
 <select name="limit" class="subtype" size="1">
 <option value="">Tous</option>
 <option value="Biography-code:y">not a biography</option>
 <option value="Biography-code:a">autobiography</option>
 <option value="Biography-code:b">biographie individuelle</option>
 <option value="Biography-code:c">biographie collective</option>
 <option value="Biography-code:d">contains biographical data</option>
 </select>
 </p>
 <p>
 <label>Illustration</label>
 <select name="limit" class="subtype" size="1">
 <option value="">Tous</option>
 <option value="Illustration-Code:a">illustrations</option>
 <option value="Illustration-Code:b">Cartes</option>
 <option value="Illustration-Code:c">portraits</option>
 <option value="Illustration-Code:d">cartes marines</option>
 <option value="Illustration-Code:e">plans</option>
 <option value="Illustration-Code:f">plates</option>
 <option value="Illustration-Code:g">Musique</option>
 <option value="Illustration-Code:h">fac-similé</option>
 <option value="Illustration-Code:i">armoiries</option>
 <option value="Illustration-Code:j">tableaux généalogiques</option>
 <option value="Illustration-Code:k">formulaires</option>
 <option value="Illustration-Code:l">échantillons</option>
 <option value="Illustration-Code:m">enregistrement sonore</option>
 <option value="Illustration-Code:n">transparents</option>
 <option value="Illustration-Code:o">illuminations</option>
 <option value="Illustration-Code:y">pas d'illustrations</option>
 </select>
 </p>
 <p>
 <label>Contenu</label>
 <select name="limit" class="subtype">
 <option value="" >Tous</option>
 <option value="ctype:a" >bibliographie</option>
 <option value="ctype:b" >catalogue</option>
 <option value="ctype:c" >index</option>
 <option value="ctype:d" >résumé</option>
 <option value="ctype:e" >Dictionnaire</option>
 <option value="ctype:f" >encyclopaedia</option>
 <option value="ctype:g" >répertoire</option>
 <option value="ctype:h" >project description</option>
 <option value="ctype:i" >statistiques</option>
 <option value="ctype:j" >programmed text books</option>
 <option value="ctype:k" >patent</option>
 <option value="ctype:l" >standard</option>
 <option value="ctype:m" >dissertation or thesis</option>
 <option value="ctype:n" >lois et décrets</option>
 <option value="ctype:o" >table numérique</option>
 <option value="ctype:p" >rapport technique</option>
 <option value="ctype:q" >sujet d'examen</option>
 <option value="ctype:r" >synthèse bibliographique</option>
 <option value="ctype:s" >Traités</option>
 <option value="ctype:t" >bande dessinée</option>
 <option value="ctype:v" >dissertation or thesis (revised)</option>
 <option value="ctype:w" >religious text</option>
 <option value="ctype:z" >autre</option>
 </select>
 </p>
 <p>
 <label>Types de vidéo</label>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Video-mt:a">film</option>
 <option value="Video-mt:b">projection</option>
 <option value="Video-mt:c">enregistrement vidéo</option>
 </select>
 </p>
 </fieldset>
 <fieldset>
 <legend>Périodiques</legend><p>
 <p>
 <label>Type de Périodique</label>
 <select name="limit" class="subtype">
 <option value="">Tout type</option>
 <option value="Type-Of-Serial:a">Périodique</option>
 <option value="Type-Of-Serial:b">Monographic series</option>
 <option value="Type-Of-Serial:c">Quotidien</option>
 <option value="Type-Of-Serial:e">Updating loose-leaf</option>
 <option value="Type-Of-Serial:f">Base de données</option>
 <option value="Type-Of-Serial:g">Updating website</option>
 <option value="Type-Of-Serial:z">Autres</option>
 </select>
 </p>
 <p>
 <label>Périodicité</label>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Frequency-code:a">Quotidien</option>
 <option value="Frequency-code:b">Bihebdomadaire</option>
 <option value="Frequency-code:c">Hebdomadaire</option>
 <option value="Frequency-code:d">bihebdomadaire</option>
 <option value="Frequency-code:e">Semimensuel</option>
 <option value="Frequency-code:f">Monthly</option>
 <option value="Frequency-code:g">Bimensuel</option>
 <option value="Frequency-code:h">Trimestriel</option>
 <option value="Frequency-code:i">3 fois par an</option>
 <option value="Frequency-code:j">Semiannuel</option>
 <option value="Frequency-code:k">Annuel</option>
 <option value="Frequency-code:l">Biennial</option>
 <option value="Frequency-code:m">Triannuel</option>
 <option value="Frequency-code:n">3 fois par semaine</option>
 <option value="Frequency-code:o">3 fois par mois</option>
 <option value="Frequency-code:y">Sans périodicité</option>
 <option value="Frequency-code:u">Inconnu</option>
 <option value="Frequency-code:z">Autres</option>
 </select>
 </p>
 <p>
 <label>Régularité</label>
 <select name="limit" class="subtype">
 <option value="">N'importe quelle régularité</option>
 <option value="Regularity-code:a">régulier</option>
 <option value="Regularity-code:b">Irrégulié normalisé</option>
 <option value="Regularity-code:y">Irrégulier</option>
 <option value="Regularity-code:u">inconnu</option>
 </select>
 </p>

 </fieldset>
 <fieldset>
 <legend>Image</legend><p>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Graphics-type:a">collage</option>
 <option value="Graphics-type:b">drawing</option>
 <option value="Graphics-type:c">peinture</option>
 <option value="Graphics-type:d">photomechanical reproduction</option>
 <option value="Graphics-type:e">photonegative</option>
 <option value="Graphics-type:f">photoprint</option>
 <option value="Graphics-type:h">picture</option>
 <option value="Graphics-type:i">print</option>
 <option value="Graphics-type:k">dessin technique</option>
 <option value="Graphics-type:z">autre type de graphique non-projeté</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Graphics-support:a">toile</option>
 <option value="Graphics-support:b">carte bristol</option>
 <option value="Graphics-support:c">carton/planche d'illustrations</option>
 <option value="Graphics-support:d">verre</option>
 <option value="Graphics-support:j">plaster</option>
 <option value="Graphics-support:k">isorel</option>
 <option value="Graphics-support:l">porcelaine</option>
 <option value="Graphics-support:m">pierre</option>
 <option value="Graphics-support:n">bois</option>
 <option value="Graphics-support:v">supports divers</option>
 <option value="Graphics-support:e">synthétique</option>
 <option value="Graphics-support:f">peau</option>
 <option value="Graphics-support:g">textile</option>
 <option value="Graphics-support:h">métal</option>
 <option value="Graphics-support:i">papier</option>
 <option value="Graphics-support:z">autres</option>
 <option value="Graphics-support:u">inconnu</option>
 </select>
 </p>
</fieldset>
</div>
