language: perl
perl:
#  - "5.8"
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
#  - "5.18"
#  - "5.19.2"

before_install:
#    - sudo echo 'deb http://debian.koha-community.org/koha squeeze main' >  /etc/apt/sources.list.d/koha


    - export DESTDIR=/tmp
    - export RUN_DATABASE_TESTS=no
    - export TEST_QA=1

    - cpanm --version

    - cat /etc/apt/sources.list
    - ls -l  /etc/apt/sources.list
    - sudo chmod 777 /etc/apt/sources.list
    - ls -l  /etc/apt/sources.list
    - cat /etc/apt/sources.list
    - pwd
#   - cd /tmp ; wget 

#    - sudo echo 'deb http://debian.koha-community.org/koha squeeze main' >>  /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get upgrade > /dev/null
    - sudo apt-get clean
#    - sudo apt-get install  $( < install_misc/debian.packages)



#    - sudo apt-get install perl-base
#    - sudo apt-get install perlapi
#    - sudo apt-get install perlapi-5.10.1
    - sudo apt-get install libdigest-jhash-perl
    - sudo apt-get install libchi-perl



    - sudo echo 'deb http://debian.koha-community.org/koha squeeze main' | sudo tee /etc/apt/sources.list.d/koha.list

    - wget -O - http://debian.koha-community.org/koha/gpg.asc | sudo apt-key add -


    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get clean
#


    - sudo apt-get install `cat install_misc/ubuntu.12.04.packages | cut -f1 | grep -v '#' | grep -v -e '^$'`


    - ./koha_perl_deps.pl -m -u

    - dpkg -l|grep callnum

    - sudo mysql -e 'create database koha'
    - sudo mysql -e "GRANT ALL PRIVILEGES ON koha.* TO 'kohaadmin'@'localhost' IDENTIFIED BY 'katikoan' "
    - sudo mysql -e 'flush privileges'
#    - exit

    - sudo mysql koha -e 'show processlist'

#    - curl -L http://cpanmin.us | perl - --sudo App::cpanminus

#    - cpanm --notest Devel::Cover Devel::Cover::Report::Clover

install:
#    - mv Makefile Makefile.old > /dev/null 2>&1
#    - make clean
    - source install_misc/environment_Makefile.PL
    - sudo useradd koha 
#    - sudo adduser koha1 --disabled-password

    - perl Makefile.PL
    - make > /dev/null
    - sudo make install > /dev/null


#    - export KOHA_CONF=/home/travis/build/KohaAloha/Koha-Dev/blib/KOHA_CONF_DIR/koha-conf.xml
#    - export PERL5LIB="/home/travis/build/KohaAloha/Koha-Dev:/usr/lib/perl5"
    - export KOHA_CONF=/etc/koha/koha-conf.xml
    - export PERL5LIB=/usr/share/koha/lib
    - export

#script: prove t/ t/db_dependent/Labels xt/author/icondirectories.t xt/author/podcorrectness.t xt/author/translatable-templates.t xt/author/valid-templates.t xt/permissions.t xt/yaml_valid.t

script:
    - make test
