language: perl
perl:
#  - "5.8"
#  - "5.10":
#  - "5.8"
#  - "5.8"
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
#  - "5.18"
#  - "5.19.2"

before_install:
#    - sudo echo 'deb http://debian.koha-community.org/koha squeeze main' >  /etc/apt/sources.list.d/koha

    - cpanm --version
    - perlbrew switch-off
    - cpanm --version
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - phantomjs -v 

#    - cp debian/templates/koha-sites.conf  /etc/koha/koha-sites.conf
#    - cat /etc/koha/koha-sites.conf

#    - dsdsdsa

    - export DESTDIR=/tmp
    - export RUN_DATABASE_TESTS=no
    - export TEST_QA=1


    - sudo apt-get update
    - sudo apt-get install apache2
    - ls -l /etc/apache2/ports.conf
#    - sudo echo "NameVirtualHost *:80" > /etc/apache2/ports.conf
    - sudo echo 'Listen 80' >> /etc/apache2/ports.conf
    - sudo echo 'Listen 8080' >> /etc/apache2/ports.conf
    - cat /etc/apache2/ports.conf

    - echo 1
    - dsd

    - sudo apt-get update
#    - sudo apt-get upgrade > /dev/null
    - sudo apt-get upgrade
    - sudo apt-get clean
#



    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get -q -y install mysql-server
    - mysqladmin -u root password nerfnerf

    - sudo echo 'deb http://debian.koha-community.org/koha squeeze main' | sudo tee /etc/apt/sources.list.d/koha.list

    - wget -O - http://debian.koha-community.org/koha/gpg.asc | sudo apt-key add -

    - sudo apt-get update
    - sudo apt-get install koha-common > /dev/null

    - sudo a2dissite 000-default
    - sudo a2enmod rewrite
    - sudo a2enmod deflate
    - sudo service apache2 restart

    - sudo koha-create --create-db library
    - sudo a2ensite library
    - sudo apache2ctl restart


#    - ./koha_perl_deps.pl -m -u
#    - ./misc/sax_parser_print.pl

    - mysql u root -p nerfnerf -e 'show processlist'


#    - sudo ln -s /usr/share/koha/bin/koha-zebra-ctl.sh /etc/init.d/koha-zebra-daemon
#    - sudo update-rc.d koha-zebra-daemon defaults
#    - sudo /etc/init.d/koha-zebra-daemon start

    - sudo apt-get install lynx wget
#    - lynx http://127.0.1.1:8080/
#    - lynx http://127.0.1.1:8080/

    - wget  http://127.0.1.1:80 -O opac
    - wget  http://127.0.1.1:8080 -O staff

#    - phantomjs http://127.0.1.1:8080

    - cat opac
    - cat staff

script:
#    - phantomjs testrunner.js
