language: perl

before_install:


    - sudo apt-get update
    - sudo apt-get clean

    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get -q -y install mysql-server
    - mysqladmin -u root password nerfnerf

    - sudo echo 'deb http://debian.koha-community.org/koha squeeze main' | sudo tee /etc/apt/sources.list.d/koha.list

    - wget -O - http://debian.koha-community.org/koha/gpg.asc | sudo apt-key add -

    - sudo apt-get update
    - sudo apt-get install koha-common > /dev/null

    - cat /etc/apache2/ports.conf
    - ls -l /etc/apache2/ports.conf

#    - sudo chmod 777  /etc/apache2/ports.conf
    - sudo echo 'NameVirtualHost *:80' > /etc/apache2/ports.conf
    - sudo echo 'Listen 80' >> /etc/apache2/ports.conf
    - ls -l /etc/apache2/ports.conf

    - sudo echo 'Listen 8080' >> /etc/apache2/ports.conf
    - cat /etc/apache2/ports.conf

    - sudo cp -v debian/templates/koha-sites.conf /etc/koha
    - ls -l /etc/koha
    - ls -l /etc/koha/koha-sites.conf


#    - sudo apt-get install curl
#    - cd /etc/koha
#    - curl -O  https://raw.github.com/KohaAloha/Koha-Dev/trav-packages/debian/templates/koha-sites.conf


    - sudo a2dissite 000-default
    - sudo a2enmod rewrite
    - sudo a2enmod deflate
    - sudo service apache2 restart

    - sudo koha-create --create-db lib1
    - sudo a2ensite lib1
    - sudo apache2ctl restart


    - sudo apt-get install lynx wget

    - wget  http://127.0.1.1:80 -O opac.html
    - wget  http://127.0.1.1:8080 -O staff.html


script:
    - cat opac.html
    - cat staff.html
    - echo 0
