<script type="text/javascript">
//<![CDATA[
    var MSG_DT_FIRST = _("Premier");
    var MSG_DT_LAST = _("Dernier");
    var MSG_DT_NEXT = _("Suivant");
    var MSG_DT_PREVIOUS = _("Précédent");
    var MSG_DT_EMPTY_TABLE = _("Pas de données disponibles dans la table.");
    var MSG_DT_INFO = _("Montrer de _START_ à _END_ sur _TOTAL_");
    var MSG_DT_INFO_EMPTY = _("Pas d'entrées à afficher");
    var MSG_DT_INFO_FILTERED = _("(filtré sur _MAX_ entrées totales)");
    var MSG_DT_LENGTH_MENU = _("Montrer _MENU_ entrées");
    var MSG_DT_LOADING_RECORDS = _("Chargement...");
    var MSG_DT_PROCESSING = _("En cours...");
    var MSG_DT_SEARCH = _("Chercher:");
    var MSG_DT_ZERO_RECORDS = _("Pas notice correspondante trouvée");
//]]>
</script>
