 <fieldset>
 <legend>Informations générales</legend>
 <p>
 <label>Public</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tous</option>
 <option value="aud:a">jeunesse, général</option>
 <option value="aud:b">pré-primaires (0-5)</option>
 <option value="aud:c">primary (5-8)</option>
 <option value="aud:d">enfants (9-14)</option>
 <option value="aud:e">young adult</option>
 <option value="aud:k">adult, serious</option>
 <option value="aud:m">adult, General</option>
 <option value="aud:u">inconnu</option>
 </select>
 </p>
 <p>
 <label>Impression</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tous</option>
 <option value="Material-type:r">impression normale</option>
 <option value="Material-type:d">gros caractères</option>
 <option value="Material-type:e">format journal</option>
 <option value="Material-type:f">Braille ou Moon</option>
 <option value="Material-type:g">petits caractères</option>
 <option value="Material-type:h">manuscrit</option>
 <option value="Material-type:i">multimédia</option>
 <option value="Material-type:j">impression miniature</option>
 <option value="Material-type:s">electronic ressource</option>
 <option value="Material-type:t">microform</option>
 <option value="Material-type:z">autre forme de matériel textuel</option>
 </select>
 </p>
 <p>
 <label>Literary genre</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tous</option>
 <option value="Literature-Code:a">fiction</option>
 <option value="Literature-Code:b">drame</option>
 <option value="Literature-Code:c">essais</option>
 <option value="Literature-Code:d">humour, satire</option>
 <option value="Literature-Code:e">lettres</option>
 <option value="Literature-Code:f">nouvelles</option>
 <option value="Literature-Code:g">poésie</option>
 <option value="Literature-Code:h">discours, orations</option>
 <option value="Literature-Code:i">libretto</option>
 <option value="Literature-Code:y">pas un texte littéraire</option>
 <option value="Literature-Code:z">multiple/other literary forms</option>
 </select>
 </p>
 <p>
 <label>Biographie</label>
 <select name="limit" class="subtype" size="1">
 <option value="">Tous</option>
 <option value="Biography-code:y">not a biography</option>
 <option value="Biography-code:a">autobiographie</option>
 <option value="Biography-code:b">biographie individuelle</option>
 <option value="Biography-code:c">biographie collective</option>
 <option value="Biography-code:d">contains biographical data</option>
 </select>
 </p>
 <p>
 <label>Illustration</label>
 <select name="limit" class="subtype" size="1">
 <option value="">Tous</option>
 <option value="Illustration-Code:a">illustrations</option>
 <option value="Illustration-Code:b">cartes</option>
 <option value="Illustration-Code:c">portraits</option>
 <option value="Illustration-Code:d">graphiques</option>
 <option value="Illustration-Code:e">plans</option>
 <option value="Illustration-Code:f">gravures</option>
 <option value="Illustration-Code:g">musique</option>
 <option value="Illustration-Code:h">facsimilés</option>
 <option value="Illustration-Code:i">côte de maille</option>
 <option value="Illustration-Code:j">tableaux généalogiques</option>
 <option value="Illustration-Code:k">formulaires</option>
 <option value="Illustration-Code:l">échantillons</option>
 <option value="Illustration-Code:m">enregistrement sonore</option>
 <option value="Illustration-Code:n">transparences</option>
 <option value="Illustration-Code:o">illuminations</option>
 <option value="Illustration-Code:y">sans illustrations</option>
 </select>
 </p>
 <p>
 <label>Contenu</label>
 <select name="limit" class="subtype">
 <option value="" >Tous</option>
 <option value="ctype:a" >bibliographie</option>
 <option value="ctype:b" >catalogue</option>
 <option value="ctype:c" >index</option>
 <option value="ctype:d" >résumé</option>
 <option value="ctype:e" >dictionnaire</option>
 <option value="ctype:f" >encyclopédie</option>
 <option value="ctype:g" >répertoire</option>
 <option value="ctype:h" >description de projet</option>
 <option value="ctype:i" >statistiques</option>
 <option value="ctype:j" >manuels</option>
 <option value="ctype:k" >brevet</option>
 <option value="ctype:l" >standard</option>
 <option value="ctype:m" >thèse ou mémoire</option>
 <option value="ctype:n" >lois et législation</option>
 <option value="ctype:o" >tableau de données</option>
 <option value="ctype:p" >rapport technique</option>
 <option value="ctype:q" >copie d'examen</option>
 <option value="ctype:r" >commentaires/analyses littéraires</option>
 <option value="ctype:s" >traités</option>
 <option value="ctype:t" >bande dessinnée</option>
 <option value="ctype:v" >dissertation or thesis (revised)</option>
 <option value="ctype:w" >religious text</option>
 <option value="ctype:z" >autre</option>
 </select>
 </p>
 <p>
 <label>Types de vidéo</label>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Video-mt:a">film</option>
 <option value="Video-mt:b">projection vidéo</option>
 <option value="Video-mt:c">enregistrement vidéo</option>
 </select>
 </p>
 </fieldset>
 <fieldset>
 <legend>Périodiques</legend><p>
 <p>
 <label>Type de périodique</label>
 <select name="limit" class="subtype">
 <option value="">Tout contenu</option>
 <option value="Type-Of-Serial:a">Périodique</option>
 <option value="Type-Of-Serial:b">Monographic series</option>
 <option value="Type-Of-Serial:c">Journal</option>
 <option value="Type-Of-Serial:e">Updating loose-leaf</option>
 <option value="Type-Of-Serial:f">Database</option>
 <option value="Type-Of-Serial:g">Updating website</option>
 <option value="Type-Of-Serial:z">Autre</option>
 </select>
 </p>
 <p>
 <label>Périodicité</label>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Frequency-code:a">Quotidien</option>
 <option value="Frequency-code:b">Semi-hebdomadaire</option>
 <option value="Frequency-code:c">Hebdomadaire</option>
 <option value="Frequency-code:d">Bihebdomadaire</option>
 <option value="Frequency-code:e">semi-mensuel</option>
 <option value="Frequency-code:f">Mensuel</option>
 <option value="Frequency-code:g">Bimensuel</option>
 <option value="Frequency-code:h">Trimestriel</option>
 <option value="Frequency-code:i">Trois fois par an</option>
 <option value="Frequency-code:j">Seminannuel</option>
 <option value="Frequency-code:k">Annuel</option>
 <option value="Frequency-code:l">Biennial</option>
 <option value="Frequency-code:m">Triannuel</option>
 <option value="Frequency-code:n">Trois fois par semaine</option>
 <option value="Frequency-code:o">Trois fois par mois</option>
 <option value="Frequency-code:y">Sans périodicité</option>
 <option value="Frequency-code:u">Inconnu</option>
 <option value="Frequency-code:z">Autre</option>
 </select>
 </p>
 <p>
 <label>Régularité</label>
 <select name="limit" class="subtype">
 <option value="">Toutes régularités</option>
 <option value="Regularity-code:a">regular</option>
 <option value="Regularity-code:b">normalised irregular</option>
 <option value="Regularity-code:y">irrégulier</option>
 <option value="Regularity-code:u">inconnu</option>
 </select>
 </p>

 </fieldset>
 <fieldset>
 <legend>Image</legend><p>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Graphics-type:a">collage</option>
 <option value="Graphics-type:b">dessin</option>
 <option value="Graphics-type:c">peinture</option>
 <option value="Graphics-type:d">reproduction photomécanique</option>
 <option value="Graphics-type:e">négatif photo</option>
 <option value="Graphics-type:f">impression photo</option>
 <option value="Graphics-type:h">image</option>
 <option value="Graphics-type:i">imprimé</option>
 <option value="Graphics-type:k">dessin technique</option>
 <option value="Graphics-type:z">autre type de graphique non-projeté</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Tous</option>
 <option value="Graphics-support:a">toile</option>
 <option value="Graphics-support:b">fiche bristol</option>
 <option value="Graphics-support:c">carton/illustration</option>
 <option value="Graphics-support:d">verre</option>
 <option value="Graphics-support:j">plâtre</option>
 <option value="Graphics-support:k">planche</option>
 <option value="Graphics-support:l">porcelaine</option>
 <option value="Graphics-support:m">pierre</option>
 <option value="Graphics-support:n">bois</option>
 <option value="Graphics-support:v">collection mêlée</option>
 <option value="Graphics-support:e">synthétique</option>
 <option value="Graphics-support:f">peau</option>
 <option value="Graphics-support:g">textile</option>
 <option value="Graphics-support:h">métal</option>
 <option value="Graphics-support:i">papier</option>
 <option value="Graphics-support:z">autres</option>
 <option value="Graphics-support:u">inconnu</option>
 </select>
 </p>
